repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-softwarefactory.github.io/charts

releases:

  - name: elasticstack
    namespace: prod
    chart: softeamouest-softwarefactory/elasticstack
    values:
      - "./values.yaml"
    secrets:
      - "./secrets.yaml"