environment: prod

sonarqube:
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/issuer: letsencrypt-issuer
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
    - sonarqube.k8.wildwidewest.xyz
    tls:
    - hosts:
      - sonarqube.k8.wildwidewest.xyz
      secretName: sonarqube-tls
