apiVersion: skaffold/v1beta1
kind: Config
deploy:
  helm:
    releases:
      - name: keycloak-prod
        chartPath: ../../../charts/keycloak-impl
        setValues:
          environment: keycloak
        overrides:
          environment: prod

          keycloak:
            keycloak:
              ingress:
                enabled: true
                annotations:
                  certmanager.k8s.io/issuer: letsencrypt-issuer
                  kubernetes.io/ingress.class: nginx
                  kubernetes.io/tls-acme: "true"
                path: /
                hosts:
                  - keycloak.k8.wildwidewest.xyz
                secretName: keycloak-prod-secret
                tls:
                  - hosts:
                      - keycloak.k8.wildwidewest.xyz
                    secretName: keycloak-prod-secret

              persistence:
                dbVendor: postgres
                dbHost: postgresql-prod-postgresql
                dbName: keycloak
                dbUser: keycloak
                dbPassword: keycloak