environment: prod

keycloak:
  keycloak:
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/issuer: letsencrypt-issuer
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
        - keycloak.k8.wildwidewest.xyz
      secretName: keycloak-prod-secret
      tls:
        - hosts:
            - keycloak.k8.wildwidewest.xyz
          secretName: keycloak-prod-secret

    persistence:
      deployPostgres: true
      dbVendor: postgres


