environment: prod

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/auth-secret: elasticstack-basicauthsecret
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  path: /
  hosts:
    - kibana.k8.wildwidewest.xyz
  secretName: kibana-secret
  tls:
    - hosts:
        - kibana.k8.wildwidewest.xyz
      secretName: kibana-secret