environment: prod

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
  - jenkins-prod.k8.wildwidewest.xyz
  secretName: jenkins-secret
  tls:
  - hosts:
    - jenkins-prod.k8.wildwidewest.xyz
    secretName: jenkins-secret
